### ISSUE TITLE
Pulling the Twilight Docker image fails on M1

### ISSUE THREAD

**Issue by IAmJSD** [twilight-rs/http-proxy#20]
Pulling the Docker image on M1 results in the following error:
```
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:ee6bba64bdc0a774b736115acedab65eb18ae4f75a0aa06d64c3625cb2f87153: not found
```

If you need a hand with testing patches for this, I'm around on Discord (JakeMakesStuff#0001). 👍

**Comment by spring4175** [comment]
Repro'd, you should be able to get around it by specifying the `linux/amd64` platform in your Compose file (or whatever that error message is coming from):

```yml
version: '3'

services:
  http_proxy:
    image: twilightrs/http-proxy
    platform: linux/amd64
```
